### ISSUE TITLE
Iron doors not working correctly.

### ISSUE THREAD

**Issue by NanoCats** [Tsuser1/Modern-LWC#112]
**LWC Version (/lwc admin version):**  An internal error occurred while attempting to perform this command!  (I think it's 2.1.2!)

**Server version (/version):** Running Spigot-4d2f30f-f1f3355 (MC 1.14.3)

**Short five word summary of issue:** doors no workie

**Detailed description of problem:** For about five minutes everything worked fine when I installed this plugin, however, after a few moments, Iron doors ceased to work. Left clicking in SURVIVAL works still, however, right clicking just causes it to spam the "This door has been locked by YOU" message and make a door noise.

Also, LEFT clicking a set of double doors only opens the opposite one?

EDIT: It turns out right clicking WITH AN ITEM IN HAND works?

**If there was an error in console, put it here:** (This is the error that lwc:admin version returns)
```
<02.07 02:59:04 [Server] Server thread/INFO Aeri_ issued server command: /lwc:cadmin version
02.07 02:59:04 [Server] Server thread/ERROR null
02.07 02:59:04 [Server] INFO org.bukkit.command.CommandException: Unhandled exception executing command 'lwc:cadmin' in plugin LWC v2.1.2-dd8c289
02.07 02:59:04 [Server] INFO at org.bukkit.command.PluginCommand.execute(PluginCommand.java:47) ~[spigot-1.14.3.jar:git-Spigot-4d2f30f-f1f3355]
02.07 02:59:04 [Server] INFO at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:149) ~[spigot-1.14.3.jar:git-Spigot-4d2f30f-f1f3355]
02.07 02:59:04 [Server] INFO at org.bukkit.craftbukkit.v1_14_R1.CraftServer.dispatchCommand(CraftServer.java:707) ~[spigot-1.14.3.jar:git-Spigot-4d2f30f-f1f3355]
02.07 02:59:04 [Server] INFO at net.minecraft.server.v1_14_R1.PlayerConnection.handleCommand(PlayerConnection.java:1670) ~[spigot-1.14.3.jar:git-Spigot-4d2f30f-f1f3355]
02.07 02:59:04 [Server] INFO at net.minecraft.server.v1_14_R1.PlayerConnection.a(PlayerConnection.java:1510) ~[spigot-1.14.3.jar:git-Spigot-4d2f30f-f1f3355]
02.07 02:59:04 [Server] INFO at net.minecraft.server.v1_14_R1.PacketPlayInChat.a(PacketPlayInChat.java:47) ~[spigot-1.14.3.jar:git-Spigot-4d2f30f-f1f3355]
02.07 02:59:04 [Server] INFO at net.minecraft.server.v1_14_R1.PacketPlayInChat.a(PacketPlayInChat.java:1) ~[spigot-1.14.3.jar:git-Spigot-4d2f30f-f1f3355]
02.07 02:59:04 [Server] INFO at net.minecraft.server.v1_14_R1.PlayerConnectionUtils.lambda$0(PlayerConnectionUtils.java:13) ~[spigot-1.14.3.jar:git-Spigot-4d2f30f-f1f3355]
02.07 02:59:04 [Server] INFO at net.minecraft.server.v1_14_R1.TickTask.run(SourceFile:18) [spigot-1.14.3.jar:git-Spigot-4d2f30f-f1f3355]
02.07 02:59:04 [Server] INFO at net.minecraft.server.v1_14_R1.IAsyncTaskHandler.executeTask(SourceFile:135) [spigot-1.14.3.jar:git-Spigot-4d2f30f-f1f3355]
02.07 02:59:04 [Server] INFO at net.minecraft.server.v1_14_R1.IAsyncTaskHandlerReentrant.executeTask(SourceFile:23) [spigot-1.14.3.jar:git-Spigot-4d2f30f-f1f3355]
02.07 02:59:04 [Server] INFO at net.minecraft.server.v1_14_R1.IAsyncTaskHandler.executeNext(SourceFile:114) [spigot-1.14.3.jar:git-Spigot-4d2f30f-f1f3355]
02.07 02:59:04 [Server] INFO at net.minecraft.server.v1_14_R1.MinecraftServer.aW(MinecraftServer.java:894) [spigot-1.14.3.jar:git-Spigot-4d2f30f-f1f3355]
02.07 02:59:04 [Server] INFO at net.minecraft.server.v1_14_R1.MinecraftServer.executeNext(MinecraftServer.java:887) [spigot-1.14.3.jar:git-Spigot-4d2f30f-f1f3355]
02.07 02:59:04 [Server] INFO at net.minecraft.server.v1_14_R1.IAsyncTaskHandler.awaitTasks(SourceFile:123) [spigot-1.14.3.jar:git-Spigot-4d2f30f-f1f3355]
02.07 02:59:04 [Server] INFO at net.minecraft.server.v1_14_R1.MinecraftServer.sleepForTick(MinecraftServer.java:871) [spigot-1.14.3.jar:git-Spigot-4d2f30f-f1f3355]
02.07 02:59:04 [Server] INFO at net.minecraft.server.v1_14_R1.MinecraftServer.run(MinecraftServer.java:804) [spigot-1.14.3.jar:git-Spigot-4d2f30f-f1f3355]
02.07 02:59:04 [Server] INFO at java.lang.Thread.run(Thread.java:748) [?:1.8.0_212]
02.07 02:59:04 [Server] INFO Caused by: com.griefcraft.scripting.ModuleException: LWC Module threw an uncaught exception! LWC version: 2.1.2
02.07 02:59:04 [Server] INFO at com.griefcraft.scripting.ModuleLoader.dispatchEvent(ModuleLoader.java:391) ~[?:?]
02.07 02:59:04 [Server] INFO at com.griefcraft.lwc.LWCPlugin.onCommand(LWCPlugin.java:167) ~[?:?]
02.07 02:59:04 [Server] INFO at org.bukkit.command.PluginCommand.execute(PluginCommand.java:45) ~[spigot-1.14.3.jar:git-Spigot-4d2f30f-f1f3355]
02.07 02:59:04 [Server] INFO ... 17 more
02.07 02:59:04 [Server] INFO Caused by: java.lang.NoClassDefFoundError: org/apache/commons/io/IOUtils
02.07 02:59:04 [Server] INFO at com.griefcraft.util.Updater.getLastUpdate(Updater.java:69) ~[?:?]
02.07 02:59:04 [Server] INFO at com.griefcraft.modules.admin.AdminVersion.getVersion(AdminVersion.java:69) ~[?:?]
02.07 02:59:04 [Server] INFO at com.griefcraft.modules.admin.AdminVersion.onCommand(AdminVersion.java:64) ~[?:?]>
```

**Comment by pop4959** [comment]
There was a bug with iron doors in 2.1.2, but that is a very old version, so updating should fix it. You should also download 2.1.4-dev, which is the only version supporting MC 1.14.3 right now.

**Comment by NanoCats** [comment]
> There was a bug with iron doors in 2.1.2, but that is a very old version, so updating should fix it. You should also download 2.1.4-dev, which is the only version supporting MC 1.14.3 right now.


Might I suggest changing the latest version publicly available from SpigotMC?

2.1.2 is what comes up when I hit download, and trying to get the "Dev build" from "https://ci.zeusmainframe.ml/job/modern-lwc/" gives me Error 523 from CloudFlare

**Comment by Tsuser1** [comment]
Sorry about that, my network switch is currently having some issues— please use the officially endorsed mirror server at [the Ender Zone](https://ci.ender.zone/view/Third%20Party%20Plugins/job/Modern%20LWC/27/) build server.

The build server and all related services will come back online when a new network switch is delivered (it’s in the mail).

**Comment by pop4959** [comment]
2.1.3 is available under stable releases on the build server. 2.1.4-dev is available as well under in-development releases. Yes, the site is currently down; use the mirror.

Spigot is intentionally not updated as of right now, to not confuse people thinking that 2.1.3 is an update for MC 1.14. It is not, and so you still need to get 2.1.4-dev right now since there is no stable release. Hope that answers your question.
