### ISSUE TITLE
WorldGuard integration is broken due to WorldGuard API changes

### ISSUE THREAD

**Issue by totemo** [Tsuser1/Modern-LWC#27]
**LWC Version (/lwc admin version): 2.1.0/** built from github main branch
**Server version (/version):** 1.13-R0.1-SNAPSHOT

**Short five word summary of issue:** `NoSuchMethodError` calling `RegionContainer WorldGuardPlugin.getRegionContainer()`

**Detailed description of problem:**

We're running build 1743 of WorldGuard 7.0.0 legacy. We've enabled WorldGuard integration in `worldguard.yml`. LWC throws exceptions calling `getRegionContainer()` because it has been removed from `WorldGuardPlugin` and instead put in class `com.sk89q.worldguard.bukkit.BukkitWorldGuardPlatform` (implements internal interface `com.sk89q.worldguard.internal.platform.WorldGuardPlatform`).

To trigger the problem, simply try to protect a chest: `/cprivate r:regionname`. LWC appears to be calling the offending code for all chests, whether they have an associated region or not, so once WorldGuard integration is enabled, LWC is crippled with exceptions (nothing works).

I suspect I can do you a pull request for this one in a few days (when I get around to attempting a fix) if you would like.

**If there was an error in console, put it here:**
```
[12:16:21] [Server thread/WARN]: com.griefcraft.scripting.ModuleException: LWC Module threw an uncaught exception! LWC version: 2.1.0
[12:16:21] [Server thread/WARN]:        at com.griefcraft.scripting.ModuleLoader.dispatchEvent(ModuleLoader.java:392)
[12:16:21] [Server thread/WARN]:        at com.griefcraft.listeners.LWCBlockListener.onBlockPlaceMonitor(LWCBlockListener.java:467)
[12:16:21] [Server thread/WARN]:        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[12:16:21] [Server thread/WARN]:        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[12:16:21] [Server thread/WARN]:        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[12:16:21] [Server thread/WARN]:        at java.lang.reflect.Method.invoke(Method.java:498)
[12:16:21] [Server thread/WARN]:        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:304)
[12:16:21] [Server thread/WARN]:        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62)
[12:16:21] [Server thread/WARN]:        at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:500)
[12:16:21] [Server thread/WARN]:        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:485)
[12:16:21] [Server thread/WARN]:        at org.bukkit.craftbukkit.v1_13_R1.event.CraftEventFactory.callBlockPlaceEvent(CraftEventFactory.java:153)
[12:16:21] [Server thread/WARN]:        at net.minecraft.server.v1_13_R1.ItemStack.placeItem(ItemStack.java:204)
[12:16:21] [Server thread/WARN]:        at net.minecraft.server.v1_13_R1.PlayerInteractManager.a(PlayerInteractManager.java:505)
[12:16:21] [Server thread/WARN]:        at net.minecraft.server.v1_13_R1.PlayerConnection.a(PlayerConnection.java:1227)
[12:16:21] [Server thread/WARN]:        at net.minecraft.server.v1_13_R1.PacketPlayInUseItem.a(PacketPlayInUseItem.java:37)
[12:16:21] [Server thread/WARN]:        at net.minecraft.server.v1_13_R1.PacketPlayInUseItem.a(PacketPlayInUseItem.java:1)
[12:16:21] [Server thread/WARN]:        at net.minecraft.server.v1_13_R1.PlayerConnectionUtils.a(SourceFile:10)
[12:16:21] [Server thread/WARN]:        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
[12:16:21] [Server thread/WARN]:        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
[12:16:21] [Server thread/WARN]:        at net.minecraft.server.v1_13_R1.SystemUtils.a(SourceFile:198)
[12:16:21] [Server thread/WARN]:        at net.minecraft.server.v1_13_R1.MinecraftServer.w(MinecraftServer.java:884)
[12:16:21] [Server thread/WARN]:        at net.minecraft.server.v1_13_R1.DedicatedServer.w(DedicatedServer.java:411)
[12:16:21] [Server thread/WARN]:        at net.minecraft.server.v1_13_R1.MinecraftServer.v(MinecraftServer.java:819)
[12:16:21] [Server thread/WARN]:        at net.minecraft.server.v1_13_R1.MinecraftServer.run(MinecraftServer.java:717)
[12:16:21] [Server thread/WARN]:        at java.lang.Thread.run(Thread.java:748)
[12:16:21] [Server thread/WARN]: Caused by: java.lang.NoSuchMethodError: com.sk89q.worldguard.bukkit.WorldGuardPlugin.getRegionContainer()Lcom/sk89q/worldguard/bukkit/RegionContainer;
[12:16:21] [Server thread/WARN]:        at com.griefcraft.modules.pluginsupport.WorldGuard.onRegisterProtection(WorldGuard.java:344)
[12:16:21] [Server thread/WARN]:        at com.griefcraft.scripting.ModuleLoader.dispatchEvent(ModuleLoader.java:374)
[12:16:21] [Server thread/WARN]:        ... 24 more
```

**Comment by pop4959** [comment]
Yes it looks like that is a problem. Simply updating the dependency and function calls should probably fix it. Since the latest version of LWC doesn't support versions of MineCraft prior to 1.13, you don't have to worry about backwards compatibility with older versions of WorldGuard.

Feel free to make a pull request. It's probably better if you do it anyway, since I have no current experience with the WorldGuard integration. I would expect that you would do a better job than me at testing it.

**Comment by pop4959** [comment]
This should be fixed in development build 43.

**Comment by totemo** [comment]
Thanks for fixing this and sorry I didn't get time to work on it myself, @pop4959. I will try out build 43.
