### ISSUE TITLE
LWC unable to add new block to lwc_blocks (SQL)

### ISSUE THREAD

**Issue by TheTopCz** [Tsuser1/Modern-LWC#29]
LWC: 2.1.0

This server is running CraftBukkit version git-Spigot-0ede7d0-c88ae6b (MC: 1.13.1) (Implementing API version 1.13.1-R0.1-SNAPSHOT) 

```
[20:05:01 INFO]: [LWC] Unable to add new block to lwc_blocks!
[20:05:01 WARN]: java.sql.SQLException: statement is not executing
[20:05:01 WARN]: at org.sqlite.core.CoreStatement.checkOpen(CoreStatement.java:50)
[20:05:01 WARN]: at org.sqlite.core.CorePreparedStatement.batch(CorePreparedStatement.java:123)
[20:05:01 WARN]: at org.sqlite.jdbc3.JDBC3PreparedStatement.setInt(JDBC3PreparedStatement.java:329)
[20:05:01 WARN]: at com.griefcraft.cache.BlockCache.addBlock(BlockCache.java:148)
[20:05:01 WARN]: at com.griefcraft.cache.BlockCache.getBlockId(BlockCache.java:253)
[20:05:01 WARN]: at com.griefcraft.cache.BlockCache.getBlockId(BlockCache.java:277)
[20:05:01 WARN]: at com.griefcraft.listeners.LWCBlockListener.onBlockPlaceMonitor(LWCBlockListener.java:476)
[20:05:01 WARN]: at sun.reflect.GeneratedMethodAccessor367.invoke(Unknown Source)
[20:05:01 WARN]: at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[20:05:01 WARN]: at java.lang.reflect.Method.invoke(Method.java:498)
[20:05:01 WARN]: at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:304)
[20:05:01 WARN]: at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62)
[20:05:01 WARN]: at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:500)
[20:05:01 WARN]: at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:485)
[20:05:01 WARN]: at org.bukkit.craftbukkit.v1_13_R2.event.CraftEventFactory.callBlockPlaceEvent(CraftEventFactory.java:153)
[20:05:01 WARN]: at net.minecraft.server.v1_13_R2.ItemStack.placeItem(ItemStack.java:204)
[20:05:01 WARN]: at net.minecraft.server.v1_13_R2.PlayerInteractManager.a(PlayerInteractManager.java:505)
[20:05:01 WARN]: at net.minecraft.server.v1_13_R2.PlayerConnection.a(PlayerConnection.java:1240)
[20:05:01 WARN]: at net.minecraft.server.v1_13_R2.PacketPlayInUseItem.a(PacketPlayInUseItem.java:37)
[20:05:01 WARN]: at net.minecraft.server.v1_13_R2.PacketPlayInUseItem.a(PacketPlayInUseItem.java:1)
[20:05:01 WARN]: at net.minecraft.server.v1_13_R2.PlayerConnectionUtils.a(SourceFile:10)
[20:05:01 WARN]: at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
[20:05:01 WARN]: at java.util.concurrent.FutureTask.run(FutureTask.java:266)
[20:05:01 WARN]: at net.minecraft.server.v1_13_R2.SystemUtils.a(SourceFile:199)
[20:05:01 WARN]: at net.minecraft.server.v1_13_R2.MinecraftServer.b(MinecraftServer.java:896)
[20:05:01 WARN]: at net.minecraft.server.v1_13_R2.DedicatedServer.b(DedicatedServer.java:411)
[20:05:01 WARN]: at net.minecraft.server.v1_13_R2.MinecraftServer.a(MinecraftServer.java:831)
[20:05:01 WARN]: at net.minecraft.server.v1_13_R2.MinecraftServer.run(MinecraftServer.java:729)
[20:05:01 WARN]: at java.lang.Thread.run(Thread.java:748)
[20:05:01 WARN]: SemtexLP moved too quickly! 29.25317178960904,4.563734563644815,-24.296771358947126
[20:05:01 WARN]: xX_vasek_Xx moved too quickly! -7.1491929487615735,-2.0013359791121417,-7.050513342610714
```

**Comment by pop4959** [comment]
I can't help you unless you follow the issue template. You must provide a description of your issue. I cannot help fix this problem unless you give me more information.

From the error, it looks like it is an SQL problem and not an LWC problem. Have you tried restarting your server? Did you reload the plugin(s) on your server before this error occurred? If you can give me exact steps to re-produce the issue, that would be ideal. It may also be helpful for you to share your core.yml file via [hastebin](https://hastebin.com/).

Thanks

**Comment by pop4959** [comment]
Closing as invalid since you have not followed the issue template, no one else seems to be reporting this issue, and the stack trace seems to indicate this is a problem with your SQL connection and not with LWC.
