### ISSUE TITLE
critical error ID: PLAYER_INTERACT

### ISSUE THREAD

**Issue by M1904** [Tsuser1/Modern-LWC#33]
**LWC Version: **ModernLWC2.1.0 

**Server version: **1.13.1 

**Short five word summary of issue:** PLAYER_INTERACT error

**Detailed description of problem:** We cannot create new protections. existing protections work fine.
is there an problem with worldedit vectors?

**If there was an error in console, put it here:**

```
[22:28:30] [Server thread/WARN]: com.griefcraft.scripting.ModuleException: LWC Module threw an uncaught exception! LWC version: 
[22:28:30] [Server thread/WARN]: 	at com.griefcraft.scripting.ModuleLoader.dispatchEvent(ModuleLoader.java:389)
[22:28:30] [Server thread/WARN]: 	at com.griefcraft.listeners.LWCPlayerListener.onPlayerInteract(LWCPlayerListener.java:687)
[22:28:30] [Server thread/WARN]: 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[22:28:30] [Server thread/WARN]: 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[22:28:30] [Server thread/WARN]: 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[22:28:30] [Server thread/WARN]: 	at java.lang.reflect.Method.invoke(Method.java:498)
[22:28:30] [Server thread/WARN]: 	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:304)
[22:28:30] [Server thread/WARN]: 	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62)
[22:28:30] [Server thread/WARN]: 	at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:500)
[22:28:30] [Server thread/WARN]: 	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:485)
[22:28:30] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_13_R2.event.CraftEventFactory.callPlayerInteractEvent(CraftEventFactory.java:238)
[22:28:30] [Server thread/WARN]: 	at net.minecraft.server.v1_13_R2.PlayerInteractManager.a(PlayerInteractManager.java:452)
[22:28:30] [Server thread/WARN]: 	at net.minecraft.server.v1_13_R2.PlayerConnection.a(PlayerConnection.java:1240)
[22:28:30] [Server thread/WARN]: 	at net.minecraft.server.v1_13_R2.PacketPlayInUseItem.a(PacketPlayInUseItem.java:37)
[22:28:30] [Server thread/WARN]: 	at net.minecraft.server.v1_13_R2.PacketPlayInUseItem.a(PacketPlayInUseItem.java:1)
[22:28:30] [Server thread/WARN]: 	at net.minecraft.server.v1_13_R2.PlayerConnectionUtils.a(SourceFile:10)
[22:28:30] [Server thread/WARN]: 	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
[22:28:30] [Server thread/WARN]: 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
[22:28:30] [Server thread/WARN]: 	at net.minecraft.server.v1_13_R2.SystemUtils.a(SourceFile:199)
[22:28:30] [Server thread/WARN]: 	at net.minecraft.server.v1_13_R2.MinecraftServer.b(MinecraftServer.java:900)
[22:28:30] [Server thread/WARN]: 	at net.minecraft.server.v1_13_R2.DedicatedServer.b(DedicatedServer.java:411)
[22:28:30] [Server thread/WARN]: 	at net.minecraft.server.v1_13_R2.MinecraftServer.a(MinecraftServer.java:835)
[22:28:30] [Server thread/WARN]: 	at net.minecraft.server.v1_13_R2.MinecraftServer.run(MinecraftServer.java:733)
[22:28:30] [Server thread/WARN]: 	at java.lang.Thread.run(Thread.java:748)
[22:28:30] [Server thread/WARN]: Caused by: com.griefcraft.scripting.ModuleException: LWC Module threw an uncaught exception! LWC version: 
[22:28:30] [Server thread/WARN]: 	at com.griefcraft.scripting.ModuleLoader.dispatchEvent(ModuleLoader.java:389)
[22:28:30] [Server thread/WARN]: 	at com.griefcraft.modules.create.CreateModule.onBlockInteract(CreateModule.java:132)
[22:28:30] [Server thread/WARN]: 	at com.griefcraft.scripting.ModuleLoader.dispatchEvent(ModuleLoader.java:357)
[22:28:30] [Server thread/WARN]: 	... 23 more
[22:28:30] [Server thread/WARN]: Caused by: java.lang.NullPointerException
[22:28:30] [Server thread/WARN]: 	at com.griefcraft.modules.pluginsupport.WorldGuard.onRegisterProtection(WorldGuard.java:348)
[22:28:30] [Server thread/WARN]: 	at com.griefcraft.scripting.ModuleLoader.dispatchEvent(ModuleLoader.java:371)
[22:28:30] [Server thread/WARN]: 	... 25 more

```

**Comment by pop4959** [comment]
@M1904 Are you using WorldGuard 7 (if so, what version)? Is `enabled` set to `true` in your `worldguard.yml` file? This might be a similar issue to #27.

When do you get this error? Is it just when placing down chests?

Thanks

**Comment by M1904** [comment]
enabled was set to true.
our worldguard is 7.0.0-SNAPSHOT;1744-8e819f7

when i place the Chest with auto-lock: private in the LWC-config
the error is also if i use the command /lock and click on the block (chest, door etc)

**Comment by pop4959** [comment]
Thank you for the quick response and details, I will check this out as soon as I find the time. The author of the issue I mentioned earlier had wanted to fix this 4 days ago but I think they might have forgotten about it.

**Comment by M1904** [comment]
thank you :)

**Comment by pop4959** [comment]
No problem. Just curious, are you using the WorldGuard regions for land protection? If not, you might be able to fix this just by setting `enabled` to false for now.

**Comment by M1904** [comment]
yes, we use worldguard for land-protection. we "sell" self-created plots (different sizes) for ingame-money. I know, the chests saved by worldguard, but every member of these plot can also use the chest. A privat chest / door is not possible without LWC.

**Comment by M1904** [comment]
no special command, we create the region with worldguard-command "/rg define"
then i put the chest on this region and the error comes in red "critical error. please contact the admin ID: PLAYER_INTERACT"
but this problem is not only at chests oder auto-lock
it's also concern doors or furnaces at the click-Event after the "/lock"-command

**Comment by Castiella** [comment]
I'm having this same issue, but with locking item frames. Our WorldGuard.Yml is set to false. :)

**Comment by pop4959** [comment]
@Castiella You might want to try the latest development build (you can find it hidden on the spigot resource page). It fixed an issue with entity locking, which has a similar (but different) error than the above.

**Comment by Castiella** [comment]
I updated to the newest dev build, and now i'm having a new issue where when we /lock an item frame the item frame just pops off the wall, would you like me to set a new issue for this?

**Comment by Castiella** [comment]
Sorry, ignore last comment, newest dev build has fixed it, thank you

**Comment by pop4959** [comment]
@M1904 Try development build 43, it should work now. Let me know if there's any problem with it. Viel Spaß!

**Comment by M1904** [comment]
do you understand german?
the same problem, sry. tested with #43 and #44
...
[10:01:45] [Server thread/INFO]: Minecrafter1904 issued server command: /lock
[10:01:46] [Server thread/WARN]: com.griefcraft.scripting.ModuleException: LWC Module threw an uncaught exception! LWC version: 
[10:01:46] [Server thread/WARN]: 	at com.griefcraft.scripting.ModuleLoader.dispatchEvent(ModuleLoader.java:389)
[10:01:46] [Server thread/WARN]: 	at com.griefcraft.listeners.LWCPlayerListener.onPlayerInteract(LWCPlayerListener.java:687)
[10:01:46] [Server thread/WARN]: 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[10:01:46] [Server thread/WARN]: 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[10:01:46] [Server thread/WARN]: 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[10:01:46] [Server thread/WARN]: 	at java.lang.reflect.Method.invoke(Method.java:498)
[10:01:46] [Server thread/WARN]: 	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:304)
[10:01:46] [Server thread/WARN]: 	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62)
[10:01:46] [Server thread/WARN]: 	at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:500)
[10:01:46] [Server thread/WARN]: 	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:485)
[10:01:46] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_13_R2.event.CraftEventFactory.callPlayerInteractEvent(CraftEventFactory.java:238)
[10:01:46] [Server thread/WARN]: 	at net.minecraft.server.v1_13_R2.PlayerInteractManager.a(PlayerInteractManager.java:452)
[10:01:46] [Server thread/WARN]: 	at net.minecraft.server.v1_13_R2.PlayerConnection.a(PlayerConnection.java:1240)
[10:01:46] [Server thread/WARN]: 	at net.minecraft.server.v1_13_R2.PacketPlayInUseItem.a(PacketPlayInUseItem.java:37)
[10:01:46] [Server thread/WARN]: 	at net.minecraft.server.v1_13_R2.PacketPlayInUseItem.a(PacketPlayInUseItem.java:1)
[10:01:46] [Server thread/WARN]: 	at net.minecraft.server.v1_13_R2.PlayerConnectionUtils.a(SourceFile:10)
[10:01:46] [Server thread/WARN]: 	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
[10:01:46] [Server thread/WARN]: 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
[10:01:46] [Server thread/WARN]: 	at net.minecraft.server.v1_13_R2.SystemUtils.a(SourceFile:199)
[10:01:46] [Server thread/WARN]: 	at net.minecraft.server.v1_13_R2.MinecraftServer.b(MinecraftServer.java:900)
[10:01:46] [Server thread/WARN]: 	at net.minecraft.server.v1_13_R2.DedicatedServer.b(DedicatedServer.java:411)
[10:01:46] [Server thread/WARN]: 	at net.minecraft.server.v1_13_R2.MinecraftServer.a(MinecraftServer.java:835)
[10:01:46] [Server thread/WARN]: 	at net.minecraft.server.v1_13_R2.MinecraftServer.run(MinecraftServer.java:733)
[10:01:46] [Server thread/WARN]: 	at java.lang.Thread.run(Thread.java:748)
[10:01:46] [Server thread/WARN]: Caused by: com.griefcraft.scripting.ModuleException: LWC Module threw an uncaught exception! LWC version: 
[10:01:46] [Server thread/WARN]: 	at com.griefcraft.scripting.ModuleLoader.dispatchEvent(ModuleLoader.java:389)
[10:01:46] [Server thread/WARN]: 	at com.griefcraft.modules.create.CreateModule.onBlockInteract(CreateModule.java:132)
[10:01:46] [Server thread/WARN]: 	at com.griefcraft.scripting.ModuleLoader.dispatchEvent(ModuleLoader.java:357)
[10:01:46] [Server thread/WARN]: 	... 23 more
[10:01:46] [Server thread/WARN]: Caused by: java.lang.NullPointerException
[10:01:46] [Server thread/WARN]: 	at com.griefcraft.modules.pluginsupport.WorldGuard.onRegisterProtection(WorldGuard.java:348)
[10:01:46] [Server thread/WARN]: 	at com.griefcraft.scripting.ModuleLoader.dispatchEvent(ModuleLoader.java:371)
[10:01:46] [Server thread/WARN]: 	... 25 more
...

**Comment by pop4959** [comment]
Yes, I can understand it. Have you tried restarting your server? I do not have that error anymore.

**Comment by M1904** [comment]
okay, without worldguard it works fine. which worldguard version do you use?
we use worldguard 7.0.0-Snapshot;1744-8e819f7

**Comment by pop4959** [comment]
@M1904 Use the latest one. I used WG 1744 + LWC 43 to test it.

**Comment by pop4959** [comment]
@M1904 mach ich gerne :)

enjoy, don't forget to update to full 2.1.1 when it comes out

**Comment by M1904** [comment]
believe me, i don't forget ;) have a nice day :)
you've made my day :)
