### ISSUE TITLE
Issue when enabling Modern LWC 2.1.1

### ISSUE THREAD

**Issue by andrewkm** [Tsuser1/Modern-LWC#54]
**LWC Version (/lwc admin version):** 
Using 2.1.1 from the spigot page.
**Server version (/version):** 
1.13.1 - Paper - Build 373
**MySQL version:** 
5.7.23
**Short five word summary of issue:** 
Issue when enabling Modern LWC 2.1.1 related to mysql.
**Detailed description of problem:**
Short description basically describes my problem.
I've tried dropping the tables, recreating them, nothing works, issue constantly happens.
Core.yml file: https://pastebin.com/raw/7fakXaye (private info obviously not shown)
When running *lwc admin report* it seems the database does connect properly.
(Yes in the below screenshot I'm testing on the latest dev build).
https://i.imgur.com/bluVY74.png

**If there was an error in console, put it here:**
```
[11:48:48] [Server thread/INFO]: [LWC] Enabling LWC v2.1.1-46e9fa0
[11:48:48] [Server thread/INFO]: [LWC] Connecting to MySQL
[11:48:48] [Server thread/WARN]: java.lang.NullPointerException
[11:48:48] [Server thread/WARN]: 	at com.griefcraft.cache.BlockCache.loadBlocks(BlockCache.java:110)
[11:48:48] [Server thread/WARN]: 	at com.griefcraft.sql.PhysDB.load(PhysDB.java:418)
[11:48:48] [Server thread/WARN]: 	at com.griefcraft.lwc.LWC.load(LWC.java:1685)
[11:48:48] [Server thread/WARN]: 	at com.griefcraft.lwc.LWCPlugin.onEnable(LWCPlugin.java:282)
[11:48:48] [Server thread/WARN]: 	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:264)
[11:48:48] [Server thread/WARN]: 	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:325)
[11:48:48] [Server thread/WARN]: 	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:405)
[11:48:48] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_13_R2.CraftServer.enablePlugin(CraftServer.java:438)
[11:48:48] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_13_R2.CraftServer.enablePlugins(CraftServer.java:352)
[11:48:48] [Server thread/WARN]: 	at net.minecraft.server.v1_13_R2.DedicatedServer.init(DedicatedServer.java:236)
[11:48:48] [Server thread/WARN]: 	at net.minecraft.server.v1_13_R2.MinecraftServer.run(MinecraftServer.java:791)
[11:48:48] [Server thread/WARN]: 	at java.lang.Thread.run(Unknown Source)
```

**Comment by pop4959** [comment]
That error should never occur under normal usage of the plugin. Have you checked that there are no other LWC jar files in your plugins folder, and that there are no other plugins that might conflict with its loading? Also make sure to restart the server in favour of reloading it manually.

Am I correct in assuming you are creating a new database? If you have dropped all four tables, LWC should create new ones for you.  Although, I don't really think the tables are an issue here.

**Comment by pop4959** [comment]
Marking as invalid since this occurs due to a plugin conflict. Please feel free to continue discussing this on Discord with me if you need assistance. I am willing to help, however since this is not an issue with LWC itself, I will now close this issue.
