### ISSUE TITLE
 Database issues

### ISSUE THREAD

**Issue by ZombieZone69** [Tsuser1/Modern-LWC#63]
in advance sorry for my english...
**LWC Version (/lwc admin version):** ModernLWC-2.1.1-46e9fa0
**Server version (/version):** Paper version git-Paper-409 (MC: 1.13.2) (Implementing API version 1.13.2-R0.1-SNAPSHOT)
**Short five word summary of issue:** When loading an error related to the database appears
**Detailed description of problem:**
I noticed that no error appear when I start the server with a blank database.
But with the old one ive got a few
(this db has traveled a lot of older versions of the plugin)
**If there was an error in console, put it here:**
```
[LWC] Enabling LWC v2.1.1-46e9fa0
[LWC] Connecting to SQLite
[LWC] Performing database optimization for 1.13...
java.lang.IllegalArgumentException: Name cannot be null
	at org.apache.commons.lang.Validate.notNull(Validate.java:192)
	at org.bukkit.Material.matchMaterial(Material.java:2824)
	at org.bukkit.Material.matchMaterial(Material.java:2809)
	at com.griefcraft.cache.BlockCache.addBlock(BlockCache.java:168)
	at com.griefcraft.sql.PhysDB.doUpdateModernLWC(PhysDB.java:2192)
	at com.griefcraft.sql.PhysDB.load(PhysDB.java:414)
	at com.griefcraft.lwc.LWC.load(LWC.java:1685)
	at com.griefcraft.lwc.LWCPlugin.onEnable(LWCPlugin.java:282)
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:264)
	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:325)
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:405)
	at org.bukkit.craftbukkit.v1_13_R2.CraftServer.enablePlugin(CraftServer.java:438)
	at org.bukkit.craftbukkit.v1_13_R2.CraftServer.enablePlugins(CraftServer.java:352)
	at net.minecraft.server.v1_13_R2.DedicatedServer.init(DedicatedServer.java:236)
	at net.minecraft.server.v1_13_R2.MinecraftServer.run(MinecraftServer.java:791)
	at java.lang.Thread.run(Thread.java:748)
```

**Comment by pop4959** [comment]
@ZombieZone69 What versions of LWC has this database gone through? Doesn't need to be exact, but it would help to know. The database migration is designed to work if you are upgrading a database that matches the format used by LWC 1.9.4 or 2.0.7. Based on the message you received, it looks like you are upgrading from LWC 2.0.7. You can find more information about the database migration [here](https://github.com/Tsuser1/Modern-LWC/wiki/MineCraft-1.13).

It might also help if you can provide a screenshot of what the protections table of your database looks like. Not the entire table, but if there are any segments where name is null (as implied by the error), please show the entire section of the table around that row.

**Comment by ZombieZone69** [comment]
Thank's for the fast answer.
I don't really remember versions that i've used, but i think all of them between 1.9.4 and 2.1.1.
For the migration process I also tried everything your link shows and nothing change.

Here is an example of the database, I do not know if it will be enough for you to understand, that's why I add a WeTransfer link to download db if necessary.
[https://we.tl/t-EbTFOTryC1](url)
![image](https://user-images.githubusercontent.com/44711899/47945658-c5217400-df03-11e8-9bf2-91b88cf54561.png)

**Comment by ZombieZone69** [comment]
@pop4959 Thank you, I will wait for your solution but I remain available if needed ;)

**Comment by pop4959** [comment]
@ZombieZone69 Can you try development build 68? It should fix the issues you are having.

**Comment by ZombieZone69** [comment]
@pop4959 Yep, I confirm the problem has been fixed with the build 68. Thanks a lot for your hardwork, and I hope that will continue ;)
