### ISSUE TITLE
Keepalive

### ISSUE THREAD

**Issue by 0xC1A551C** [Tsuser1/Modern-LWC#71]
**LWC Version (/lwc admin version):** 2.1.1 
**Server version (/version):**  1.13.2

**Short five word summary of issue:** 
Seems like a ping keepalive issue. What could cause this? Happened randomly after a reboot.

**Detailed description of problem:**

`
[13:33:49 INFO]: [LWC] Keepalive packet (ping) failed!

[13:33:49 WARN]: com.mysql.jdbc.exceptions.jdbc4.CommunicationsException: Communications link failure

[13:33:49 WARN]: 

[13:33:49 WARN]: The last packet successfully received from the server was 300,041 milliseconds ago.  The last packet sent successfully to the server was 1 milliseconds ago.

[13:33:49 WARN]: 	at sun.reflect.GeneratedConstructorAccessor164.newInstance(Unknown Source)

[13:33:49 WARN]: 	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)

[13:33:49 WARN]: 	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)

[13:33:49 WARN]: 	at com.mysql.jdbc.Util.handleNewInstance(Util.java:425)

[13:33:49 WARN]: 	at com.mysql.jdbc.SQLError.createCommunicationsException(SQLError.java:990)

[13:33:49 WARN]: 	at com.mysql.jdbc.MysqlIO.reuseAndReadPacket(MysqlIO.java:3562)

[13:33:49 WARN]: 	at com.mysql.jdbc.MysqlIO.reuseAndReadPacket(MysqlIO.java:3462)

[13:33:49 WARN]: 	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3905)

[13:33:49 WARN]: 	at com.mysql.jdbc.MysqlIO.sendCommand(MysqlIO.java:2530)

[13:33:49 WARN]: 	at com.mysql.jdbc.MysqlIO.sqlQueryDirect(MysqlIO.java:2683)

[13:33:49 WARN]: 	at com.mysql.jdbc.ConnectionImpl.execSQL(ConnectionImpl.java:2491)

[13:33:49 WARN]: 	at com.mysql.jdbc.ConnectionImpl.execSQL(ConnectionImpl.java:2449)

[13:33:49 WARN]: 	at com.mysql.jdbc.StatementImpl.executeQuery(StatementImpl.java:1381)

[13:33:49 WARN]: 	at com.griefcraft.sql.Database.pingDatabase(Database.java:149)

[13:33:49 WARN]: 	at com.griefcraft.util.DatabaseThread.flushDatabase(DatabaseThread.java:161)

[13:33:49 WARN]: 	at com.griefcraft.util.DatabaseThread.run(DatabaseThread.java:179)

[13:33:49 WARN]: 	at java.lang.Thread.run(Thread.java:748)

[13:33:49 WARN]: Caused by: java.io.EOFException: Can not read response from server. Expected to read 4 bytes, read 0 bytes before connection was unexpectedly lost.

[13:33:49 WARN]: 	at com.mysql.jdbc.MysqlIO.readFully(MysqlIO.java:3014)

[13:33:49 WARN]: 	at com.mysql.jdbc.MysqlIO.reuseAndReadPacket(MysqlIO.java:3472)

[13:33:49 WARN]: 	... 11 more`

**Comment by 0xC1A551C** [comment]
Oops can be closed. Mysql server restarted at this same time.

**Comment by pop4959** [comment]
@0xC1A551C Glad you managed to fix the issue. As for context, the keep-alive exists to prevent the database connection from timing out due to inactivity. It is a simple query which will ping the database at regular intervals. As such, if the query fails you will see an error. This can happen if the database connection was broken by some means.
