### ISSUE TITLE
Protections not working

### ISSUE THREAD

**Issue by scysys** [Tsuser1/Modern-LWC#74]
**LWC Version (/lwc admin version):** 2.1.1

**Server version (/version):** 1.13.2

**Short five word summary of issue:** 
Can't make an Protection

**Detailed description of problem:**
See Output. Not sure it is really an LWC Error or something beside WorldEdit.

**If there was an error in console, put it here:**
```
[13:29:56 INFO]: scysys issued server command: /cprivate
[13:30:04 WARN]: com.griefcraft.scripting.ModuleException: LWC Module threw an uncaught exception! LWC version: 2.1.1
[13:30:04 WARN]: 	at com.griefcraft.scripting.ModuleLoader.dispatchEvent(ModuleLoader.java:391)
[13:30:04 WARN]: 	at com.griefcraft.listeners.LWCPlayerListener.onPlayerInteract(LWCPlayerListener.java:685)
[13:30:04 WARN]: 	at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor21.execute(Unknown Source)
[13:30:04 WARN]: 	at org.bukkit.plugin.EventExecutor$2.execute(EventExecutor.java:70)
[13:30:04 WARN]: 	at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:78)
[13:30:04 WARN]: 	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62)
[13:30:04 WARN]: 	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:513)
[13:30:04 WARN]: 	at org.bukkit.craftbukkit.v1_13_R2.event.CraftEventFactory.callPlayerInteractEvent(CraftEventFactory.java:315)
[13:30:04 WARN]: 	at org.bukkit.craftbukkit.v1_13_R2.event.CraftEventFactory.callPlayerInteractEvent(CraftEventFactory.java:282)
[13:30:04 WARN]: 	at net.minecraft.server.v1_13_R2.PlayerInteractManager.a(PlayerInteractManager.java:110)
[13:30:04 WARN]: 	at net.minecraft.server.v1_13_R2.PlayerConnection.a(PlayerConnection.java:1277)
[13:30:04 WARN]: 	at net.minecraft.server.v1_13_R2.PacketPlayInBlockDig.a(SourceFile:40)
[13:30:04 WARN]: 	at net.minecraft.server.v1_13_R2.PacketPlayInBlockDig.a(SourceFile:10)
[13:30:04 WARN]: 	at net.minecraft.server.v1_13_R2.PlayerConnectionUtils.lambda$ensureMainThread$0(PlayerConnectionUtils.java:12)
[13:30:04 WARN]: 	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
[13:30:04 WARN]: 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
[13:30:04 WARN]: 	at net.minecraft.server.v1_13_R2.SystemUtils.a(SystemUtils.java:109)
[13:30:04 WARN]: 	at net.minecraft.server.v1_13_R2.MinecraftServer.b(MinecraftServer.java:1016)
[13:30:04 WARN]: 	at net.minecraft.server.v1_13_R2.DedicatedServer.b(DedicatedServer.java:439)
[13:30:04 WARN]: 	at net.minecraft.server.v1_13_R2.MinecraftServer.a(MinecraftServer.java:943)
[13:30:04 WARN]: 	at net.minecraft.server.v1_13_R2.MinecraftServer.run(MinecraftServer.java:841)
[13:30:04 WARN]: 	at java.lang.Thread.run(Thread.java:748)
[13:30:04 WARN]: Caused by: com.griefcraft.scripting.ModuleException: LWC Module threw an uncaught exception! LWC version: 2.1.1
[13:30:04 WARN]: 	at com.griefcraft.scripting.ModuleLoader.dispatchEvent(ModuleLoader.java:391)
[13:30:04 WARN]: 	at com.griefcraft.modules.create.CreateModule.onBlockInteract(CreateModule.java:130)
[13:30:04 WARN]: 	at com.griefcraft.scripting.ModuleLoader.dispatchEvent(ModuleLoader.java:359)
[13:30:04 WARN]: 	... 21 more
[13:30:04 WARN]: Caused by: java.lang.NoSuchMethodError: com.sk89q.worldedit.bukkit.BukkitAdapter.asVector(Lorg/bukkit/Location;)Lcom/sk89q/worldedit/Vector;
[13:30:04 WARN]: 	at com.griefcraft.modules.pluginsupport.WorldGuard.onRegisterProtection(WorldGuard.java:359)
[13:30:04 WARN]: 	at com.griefcraft.scripting.ModuleLoader.dispatchEvent(ModuleLoader.java:373)
[13:30:04 WARN]: 	... 23 more
[13:30:45 INFO]: scysys issued server command: /cpublic
[13:30:47 WARN]: com.griefcraft.scripting.ModuleException: LWC Module threw an uncaught exception! LWC version: 2.1.1
[13:30:47 WARN]: 	at com.griefcraft.scripting.ModuleLoader.dispatchEvent(ModuleLoader.java:391)
[13:30:47 WARN]: 	at com.griefcraft.listeners.LWCPlayerListener.onPlayerInteract(LWCPlayerListener.java:685)
[13:30:47 WARN]: 	at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor21.execute(Unknown Source)
[13:30:47 WARN]: 	at org.bukkit.plugin.EventExecutor$2.execute(EventExecutor.java:70)
[13:30:47 WARN]: 	at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:78)
[13:30:47 WARN]: 	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62)
[13:30:47 WARN]: 	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:513)
[13:30:47 WARN]: 	at org.bukkit.craftbukkit.v1_13_R2.event.CraftEventFactory.callPlayerInteractEvent(CraftEventFactory.java:315)
[13:30:47 WARN]: 	at org.bukkit.craftbukkit.v1_13_R2.event.CraftEventFactory.callPlayerInteractEvent(CraftEventFactory.java:282)
[13:30:47 WARN]: 	at net.minecraft.server.v1_13_R2.PlayerInteractManager.a(PlayerInteractManager.java:110)
[13:30:47 WARN]: 	at net.minecraft.server.v1_13_R2.PlayerConnection.a(PlayerConnection.java:1277)
[13:30:47 WARN]: 	at net.minecraft.server.v1_13_R2.PacketPlayInBlockDig.a(SourceFile:40)
[13:30:47 WARN]: 	at net.minecraft.server.v1_13_R2.PacketPlayInBlockDig.a(SourceFile:10)
[13:30:47 WARN]: 	at net.minecraft.server.v1_13_R2.PlayerConnectionUtils.lambda$ensureMainThread$0(PlayerConnectionUtils.java:12)
[13:30:47 WARN]: 	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
[13:30:47 WARN]: 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
[13:30:47 WARN]: 	at net.minecraft.server.v1_13_R2.SystemUtils.a(SystemUtils.java:109)
[13:30:47 WARN]: 	at net.minecraft.server.v1_13_R2.MinecraftServer.b(MinecraftServer.java:1016)
[13:30:47 WARN]: 	at net.minecraft.server.v1_13_R2.DedicatedServer.b(DedicatedServer.java:439)
[13:30:47 WARN]: 	at net.minecraft.server.v1_13_R2.MinecraftServer.a(MinecraftServer.java:943)
[13:30:47 WARN]: 	at net.minecraft.server.v1_13_R2.MinecraftServer.run(MinecraftServer.java:841)
[13:30:47 WARN]: 	at java.lang.Thread.run(Thread.java:748)
[13:30:47 WARN]: Caused by: com.griefcraft.scripting.ModuleException: LWC Module threw an uncaught exception! LWC version: 2.1.1
[13:30:47 WARN]: 	at com.griefcraft.scripting.ModuleLoader.dispatchEvent(ModuleLoader.java:391)
[13:30:47 WARN]: 	at com.griefcraft.modules.create.CreateModule.onBlockInteract(CreateModule.java:130)
[13:30:47 WARN]: 	at com.griefcraft.scripting.ModuleLoader.dispatchEvent(ModuleLoader.java:359)
[13:30:47 WARN]: 	... 21 more
[13:30:47 WARN]: Caused by: java.lang.NoSuchMethodError: com.sk89q.worldedit.bukkit.BukkitAdapter.asVector(Lorg/bukkit/Location;)Lcom/sk89q/worldedit/Vector;
[13:30:47 WARN]: 	at com.griefcraft.modules.pluginsupport.WorldGuard.onRegisterProtection(WorldGuard.java:359)
[13:30:47 WARN]: 	at com.griefcraft.scripting.ModuleLoader.dispatchEvent(ModuleLoader.java:373)
[13:30:47 WARN]: 	... 23 more
```

**Comment by Tsuser1** [comment]
Are you using the latest beta of WorldEdit?

**Comment by pop4959** [comment]
@scysys If you have the WorldGuard integration enabled, keep in mind that LWC 2.1.1 requires WorldGuard 7 Beta 1, while the latest development builds require WorldGuard 7 Beta 2+.

The solution is probably to upgrade to LWC 2.1.2-dev, or downgrade WorldGuard to 7 Beta 1.

**Comment by pop4959** [comment]
Please download LWC 2.1.2 from the Spigot plugin page. It should fix this issue.
