### ISSUE TITLE
Duplicate entry '1' for key 'PRIMARY

### ISSUE THREAD

**Issue by almateoskott** [Tsuser1/Modern-LWC#81]
**LWC Version (/lwc admin version):** 
Main plugin: 2.1.2-dd8c289/ 
**Server version (/version):**
CraftBukkit version git-Spigot-a1ba5fe-3359cb1 (MC: 1.13.2) (Implementing API version 1.13.2-R0.1-SNAPSHOT)
**Short five word summary of issue:** 
Database error on startup
**Detailed description of problem:**
On startup there is an error of "com.mysql.jdbc.exceptions.jdbc4.MySQLIntegrityConstraintViolationException: Duplicate entry '1' for key 'PRIMARY'" with associated other errors in a small flood.  It sounds related to database changes between versions of LWC.  Potentially fixable by something that alters the database as needed the first time the 1.13.2 version 1.1.2 runs.  Or if not, maybe an update note with what to do about this.  In the actual game, what seems to happen is that existing chests work fine.  New chests cause a failure with nothing on the screen at all in the game, but a flood in the logs.  I have included the actual log entries below.

**If there was an error in console, put it here:**
```
[08:57:35] [Server thread/INFO]: [LWC] Enabling LWC v2.1.2-dd8c289
[08:57:35] [Server thread/INFO]: [LWC] Connecting to MySQL
[08:57:37] [Server thread/INFO]: [LWC] Performing database optimization for 1.13...
[08:57:37] [Server thread/INFO]: [LWC] Unable to add new block to lwc_blocks!
[08:57:37] [Server thread/WARN]: com.mysql.jdbc.exceptions.jdbc4.MySQLIntegrityConstraintViolationException: Duplicate entry '1' for key 'PRIMARY'
[08:57:37] [Server thread/WARN]: 	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
[08:57:37] [Server thread/WARN]: 	at sun.reflect.NativeConstructorAccessorImpl.newInstance(Unknown Source)
[08:57:37] [Server thread/WARN]: 	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(Unknown Source)
[08:57:37] [Server thread/WARN]: 	at java.lang.reflect.Constructor.newInstance(Unknown Source)
[08:57:37] [Server thread/WARN]: 	at com.mysql.jdbc.Util.handleNewInstance(Util.java:425)
[08:57:37] [Server thread/WARN]: 	at com.mysql.jdbc.Util.getInstance(Util.java:408)
[08:57:37] [Server thread/WARN]: 	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:936)
[08:57:37] [Server thread/WARN]: 	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3978)
[08:57:37] [Server thread/WARN]: 	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3914)
[08:57:37] [Server thread/WARN]: 	at com.mysql.jdbc.MysqlIO.sendCommand(MysqlIO.java:2530)
[08:57:37] [Server thread/WARN]: 	at com.mysql.jdbc.MysqlIO.sqlQueryDirect(MysqlIO.java:2683)
[08:57:37] [Server thread/WARN]: 	at com.mysql.jdbc.ConnectionImpl.execSQL(ConnectionImpl.java:2495)
[08:57:37] [Server thread/WARN]: 	at com.mysql.jdbc.PreparedStatement.executeInternal(PreparedStatement.java:1903)
[08:57:37] [Server thread/WARN]: 	at com.mysql.jdbc.PreparedStatement.executeUpdateInternal(PreparedStatement.java:2124)
[08:57:37] [Server thread/WARN]: 	at com.mysql.jdbc.PreparedStatement.executeUpdateInternal(PreparedStatement.java:2058)
[08:57:37] [Server thread/WARN]: 	at com.mysql.jdbc.PreparedStatement.executeLargeUpdate(PreparedStatement.java:5158)
[08:57:37] [Server thread/WARN]: 	at com.mysql.jdbc.PreparedStatement.executeUpdate(PreparedStatement.java:2043)
[08:57:37] [Server thread/WARN]: 	at com.griefcraft.cache.BlockCache.addBlock(BlockCache.java:150)
[08:57:37] [Server thread/WARN]: 	at com.griefcraft.cache.BlockCache.addBlock(BlockCache.java:170)
[08:57:37] [Server thread/WARN]: 	at com.griefcraft.sql.PhysDB.doUpdateModernLWC(PhysDB.java:2210)
[08:57:37] [Server thread/WARN]: 	at com.griefcraft.sql.PhysDB.load(PhysDB.java:414)
[08:57:37] [Server thread/WARN]: 	at com.griefcraft.lwc.LWC.load(LWC.java:1686)
[08:57:37] [Server thread/WARN]: 	at com.griefcraft.lwc.LWCPlugin.onEnable(LWCPlugin.java:282)
[08:57:37] [Server thread/WARN]: 	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:264)
[08:57:37] [Server thread/WARN]: 	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:339)
[08:57:37] [Server thread/WARN]: 	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:403)
[08:57:37] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_13_R2.CraftServer.enablePlugin(CraftServer.java:431)
[08:57:37] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_13_R2.CraftServer.enablePlugins(CraftServer.java:345)
[08:57:37] [Server thread/WARN]: 	at net.minecraft.server.v1_13_R2.DedicatedServer.init(DedicatedServer.java:214)
[08:57:37] [Server thread/WARN]: 	at net.minecraft.server.v1_13_R2.MinecraftServer.run(MinecraftServer.java:702)
[08:57:37] [Server thread/WARN]: 	at java.lang.Thread.run(Unknown Source)
[08:57:37] [Server thread/INFO]: [LWC] Unable to add new block to lwc_blocks!
[08:57:37] [Server thread/WARN]: com.mysql.jdbc.exceptions.jdbc4.MySQLIntegrityConstraintViolationException: Duplicate entry '1' for key 'PRIMARY'
[08:57:37] [Server thread/WARN]: 	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
[08:57:37] [Server thread/WARN]: 	at sun.reflect.NativeConstructorAccessorImpl.newInstance(Unknown Source)
[08:57:37] [Server thread/WARN]: 	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(Unknown Source)
[08:57:37] [Server thread/WARN]: 	at java.lang.reflect.Constructor.newInstance(Unknown Source)
[08:57:37] [Server thread/WARN]: 	at com.mysql.jdbc.Util.handleNewInstance(Util.java:425)
[08:57:37] [Server thread/WARN]: 	at com.mysql.jdbc.Util.getInstance(Util.java:408)
[08:57:37] [Server thread/WARN]: 	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:936)
[08:57:37] [Server thread/WARN]: 	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3978)
[08:57:37] [Server thread/WARN]: 	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3914)
[08:57:37] [Server thread/WARN]: 	at com.mysql.jdbc.MysqlIO.sendCommand(MysqlIO.java:2530)
[08:57:37] [Server thread/WARN]: 	at com.mysql.jdbc.MysqlIO.sqlQueryDirect(MysqlIO.java:2683)
[08:57:37] [Server thread/WARN]: 	at com.mysql.jdbc.ConnectionImpl.execSQL(ConnectionImpl.java:2495)
[08:57:37] [Server thread/WARN]: 	at com.mysql.jdbc.PreparedStatement.executeInternal(PreparedStatement.java:1903)
[08:57:37] [Server thread/WARN]: 	at com.mysql.jdbc.PreparedStatement.executeUpdateInternal(PreparedStatement.java:2124)
[08:57:37] [Server thread/WARN]: 	at com.mysql.jdbc.PreparedStatement.executeUpdateInternal(PreparedStatement.java:2058)
[08:57:37] [Server thread/WARN]: 	at com.mysql.jdbc.PreparedStatement.executeLargeUpdate(PreparedStatement.java:5158)
[08:57:37] [Server thread/WARN]: 	at com.mysql.jdbc.PreparedStatement.executeUpdate(PreparedStatement.java:2043)
[08:57:37] [Server thread/WARN]: 	at com.griefcraft.cache.BlockCache.addBlock(BlockCache.java:150)
[08:57:37] [Server thread/WARN]: 	at com.griefcraft.cache.BlockCache.addBlock(BlockCache.java:170)
[08:57:37] [Server thread/WARN]: 	at com.griefcraft.sql.PhysDB.doUpdateModernLWC(PhysDB.java:2210)
[08:57:37] [Server thread/WARN]: 	at com.griefcraft.sql.PhysDB.load(PhysDB.java:414)
[08:57:37] [Server thread/WARN]: 	at com.griefcraft.lwc.LWC.load(LWC.java:1686)
[08:57:37] [Server thread/WARN]: 	at com.griefcraft.lwc.LWCPlugin.onEnable(LWCPlugin.java:282)
[08:57:37] [Server thread/WARN]: 	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:264)
[08:57:37] [Server thread/WARN]: 	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:339)
[08:57:37] [Server thread/WARN]: 	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:403)
[08:57:37] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_13_R2.CraftServer.enablePlugin(CraftServer.java:431)
[08:57:37] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_13_R2.CraftServer.enablePlugins(CraftServer.java:345)
[08:57:37] [Server thread/WARN]: 	at net.minecraft.server.v1_13_R2.DedicatedServer.init(DedicatedServer.java:214)
[08:57:37] [Server thread/WARN]: 	at net.minecraft.server.v1_13_R2.MinecraftServer.run(MinecraftServer.java:702)
[08:57:37] [Server thread/WARN]: 	at java.lang.Thread.run(Unknown Source)
[08:57:37] [Server thread/INFO]: [LWC] Unable to add new block to lwc_blocks!
[08:57:37] [Server thread/WARN]: com.mysql.jdbc.exceptions.jdbc4.MySQLIntegrityConstraintViolationException: Duplicate entry '1' for key 'PRIMARY'
[08:57:37] [Server thread/WARN]: 	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
[08:57:37] [Server thread/WARN]: 	at sun.reflect.NativeConstructorAccessorImpl.newInstance(Unknown Source)
[08:57:37] [Server thread/WARN]: 	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(Unknown Source)
[08:57:37] [Server thread/WARN]: 	at java.lang.reflect.Constructor.newInstance(Unknown Source)
[08:57:37] [Server thread/WARN]: 	at com.mysql.jdbc.Util.handleNewInstance(Util.java:425)
[08:57:37] [Server thread/WARN]: 	at com.mysql.jdbc.Util.getInstance(Util.java:408)
[08:57:37] [Server thread/WARN]: 	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:936)
[08:57:37] [Server thread/WARN]: 	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3978)
[08:57:37] [Server thread/WARN]: 	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3914)
[08:57:37] [Server thread/WARN]: 	at com.mysql.jdbc.MysqlIO.sendCommand(MysqlIO.java:2530)
[08:57:37] [Server thread/WARN]: 	at com.mysql.jdbc.MysqlIO.sqlQueryDirect(MysqlIO.java:2683)
[08:57:37] [Server thread/WARN]: 	at com.mysql.jdbc.ConnectionImpl.execSQL(ConnectionImpl.java:2495)
[08:57:37] [Server thread/WARN]: 	at com.mysql.jdbc.PreparedStatement.executeInternal(PreparedStatement.java:1903)
[08:57:37] [Server thread/WARN]: 	at com.mysql.jdbc.PreparedStatement.executeUpdateInternal(PreparedStatement.java:2124)
[08:57:37] [Server thread/WARN]: 	at com.mysql.jdbc.PreparedStatement.executeUpdateInternal(PreparedStatement.java:2058)
[08:57:37] [Server thread/WARN]: 	at com.mysql.jdbc.PreparedStatement.executeLargeUpdate(PreparedStatement.java:5158)
[08:57:37] [Server thread/WARN]: 	at com.mysql.jdbc.PreparedStatement.executeUpdate(PreparedStatement.java:2043)
[08:57:37] [Server thread/WARN]: 	at com.griefcraft.cache.BlockCache.addBlock(BlockCache.java:150)
[08:57:37] [Server thread/WARN]: 	at com.griefcraft.cache.BlockCache.addBlock(BlockCache.java:170)
[08:57:37] [Server thread/WARN]: 	at com.griefcraft.sql.PhysDB.doUpdateModernLWC(PhysDB.java:2210)
[08:57:37] [Server thread/WARN]: 	at com.griefcraft.sql.PhysDB.load(PhysDB.java:414)
[08:57:37] [Server thread/WARN]: 	at com.griefcraft.lwc.LWC.load(LWC.java:1686)
[08:57:37] [Server thread/WARN]: 	at com.griefcraft.lwc.LWCPlugin.onEnable(LWCPlugin.java:282)
[08:57:37] [Server thread/WARN]: 	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:264)
[08:57:37] [Server thread/WARN]: 	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:339)
[08:57:37] [Server thread/WARN]: 	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:403)
[08:57:37] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_13_R2.CraftServer.enablePlugin(CraftServer.java:431)
[08:57:37] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_13_R2.CraftServer.enablePlugins(CraftServer.java:345)
[08:57:37] [Server thread/WARN]: 	at net.minecraft.server.v1_13_R2.DedicatedServer.init(DedicatedServer.java:214)
[08:57:37] [Server thread/WARN]: 	at net.minecraft.server.v1_13_R2.MinecraftServer.run(MinecraftServer.java:702)
[08:57:37] [Server thread/WARN]: 	at java.lang.Thread.run(Unknown Source)
[08:57:38] [Server thread/INFO]: [LWC] Unable to add new block to lwc_blocks!
[08:57:38] [Server thread/WARN]: com.mysql.jdbc.exceptions.jdbc4.MySQLIntegrityConstraintViolationException: Duplicate entry '1' for key 'PRIMARY'
[08:57:38] [Server thread/WARN]: 	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
[08:57:38] [Server thread/WARN]: 	at sun.reflect.NativeConstructorAccessorImpl.newInstance(Unknown Source)
[08:57:38] [Server thread/WARN]: 	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(Unknown Source)
[08:57:38] [Server thread/WARN]: 	at java.lang.reflect.Constructor.newInstance(Unknown Source)
[08:57:38] [Server thread/WARN]: 	at com.mysql.jdbc.Util.handleNewInstance(Util.java:425)
[08:57:38] [Server thread/WARN]: 	at com.mysql.jdbc.Util.getInstance(Util.java:408)
[08:57:38] [Server thread/WARN]: 	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:936)
[08:57:38] [Server thread/WARN]: 	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3978)
[08:57:38] [Server thread/WARN]: 	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3914)
[08:57:38] [Server thread/WARN]: 	at com.mysql.jdbc.MysqlIO.sendCommand(MysqlIO.java:2530)
[08:57:38] [Server thread/WARN]: 	at com.mysql.jdbc.MysqlIO.sqlQueryDirect(MysqlIO.java:2683)
[08:57:38] [Server thread/WARN]: 	at com.mysql.jdbc.ConnectionImpl.execSQL(ConnectionImpl.java:2495)
[08:57:38] [Server thread/WARN]: 	at com.mysql.jdbc.PreparedStatement.executeInternal(PreparedStatement.java:1903)
[08:57:38] [Server thread/WARN]: 	at com.mysql.jdbc.PreparedStatement.executeUpdateInternal(PreparedStatement.java:2124)
[08:57:38] [Server thread/WARN]: 	at com.mysql.jdbc.PreparedStatement.executeUpdateInternal(PreparedStatement.java:2058)
[08:57:38] [Server thread/WARN]: 	at com.mysql.jdbc.PreparedStatement.executeLargeUpdate(PreparedStatement.java:5158)
[08:57:38] [Server thread/WARN]: 	at com.mysql.jdbc.PreparedStatement.executeUpdate(PreparedStatement.java:2043)
[08:57:38] [Server thread/WARN]: 	at com.griefcraft.cache.BlockCache.addBlock(BlockCache.java:150)
[08:57:38] [Server thread/WARN]: 	at com.griefcraft.cache.BlockCache.addBlock(BlockCache.java:170)
[08:57:38] [Server thread/WARN]: 	at com.griefcraft.sql.PhysDB.doUpdateModernLWC(PhysDB.java:2210)
[08:57:38] [Server thread/WARN]: 	at com.griefcraft.sql.PhysDB.load(PhysDB.java:414)
[08:57:38] [Server thread/WARN]: 	at com.griefcraft.lwc.LWC.load(LWC.java:1686)
[08:57:38] [Server thread/WARN]: 	at com.griefcraft.lwc.LWCPlugin.onEnable(LWCPlugin.java:282)
[08:57:38] [Server thread/WARN]: 	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:264)
[08:57:38] [Server thread/WARN]: 	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:339)
[08:57:38] [Server thread/WARN]: 	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:403)
[08:57:38] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_13_R2.CraftServer.enablePlugin(CraftServer.java:431)
[08:57:38] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_13_R2.CraftServer.enablePlugins(CraftServer.java:345)
[08:57:38] [Server thread/WARN]: 	at net.minecraft.server.v1_13_R2.DedicatedServer.init(DedicatedServer.java:214)
[08:57:38] [Server thread/WARN]: 	at net.minecraft.server.v1_13_R2.MinecraftServer.run(MinecraftServer.java:702)
[08:57:38] [Server thread/WARN]: 	at java.lang.Thread.run(Unknown Source)
[08:57:38] [Server thread/INFO]: [LWC] Unable to add new block to lwc_blocks!
[08:57:38] [Server thread/WARN]: com.mysql.jdbc.exceptions.jdbc4.MySQLIntegrityConstraintViolationException: Duplicate entry '1' for key 'PRIMARY'
[08:57:38] [Server thread/WARN]: 	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
[08:57:38] [Server thread/WARN]: 	at sun.reflect.NativeConstructorAccessorImpl.newInstance(Unknown Source)
[08:57:38] [Server thread/WARN]: 	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(Unknown Source)
[08:57:38] [Server thread/WARN]: 	at java.lang.reflect.Constructor.newInstance(Unknown Source)
[08:57:38] [Server thread/WARN]: 	at com.mysql.jdbc.Util.handleNewInstance(Util.java:425)
[08:57:38] [Server thread/WARN]: 	at com.mysql.jdbc.Util.getInstance(Util.java:408)
[08:57:38] [Server thread/WARN]: 	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:936)
[08:57:38] [Server thread/WARN]: 	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3978)
[08:57:38] [Server thread/WARN]: 	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3914)
[08:57:38] [Server thread/WARN]: 	at com.mysql.jdbc.MysqlIO.sendCommand(MysqlIO.java:2530)
[08:57:38] [Server thread/WARN]: 	at com.mysql.jdbc.MysqlIO.sqlQueryDirect(MysqlIO.java:2683)
[08:57:38] [Server thread/WARN]: 	at com.mysql.jdbc.ConnectionImpl.execSQL(ConnectionImpl.java:2495)
[08:57:38] [Server thread/WARN]: 	at com.mysql.jdbc.PreparedStatement.executeInternal(PreparedStatement.java:1903)
[08:57:38] [Server thread/WARN]: 	at com.mysql.jdbc.PreparedStatement.executeUpdateInternal(PreparedStatement.java:2124)
[08:57:38] [Server thread/WARN]: 	at com.mysql.jdbc.PreparedStatement.executeUpdateInternal(PreparedStatement.java:2058)
[08:57:38] [Server thread/WARN]: 	at com.mysql.jdbc.PreparedStatement.executeLargeUpdate(PreparedStatement.java:5158)
[08:57:38] [Server thread/WARN]: 	at com.mysql.jdbc.PreparedStatement.executeUpdate(PreparedStatement.java:2043)
[08:57:38] [Server thread/WARN]: 	at com.griefcraft.cache.BlockCache.addBlock(BlockCache.java:150)
[08:57:38] [Server thread/WARN]: 	at com.griefcraft.cache.BlockCache.addBlock(BlockCache.java:170)
[08:57:38] [Server thread/WARN]: 	at com.griefcraft.sql.PhysDB.doUpdateModernLWC(PhysDB.java:2210)
[08:57:38] [Server thread/WARN]: 	at com.griefcraft.sql.PhysDB.load(PhysDB.java:414)
[08:57:38] [Server thread/WARN]: 	at com.griefcraft.lwc.LWC.load(LWC.java:1686)
[08:57:38] [Server thread/WARN]: 	at com.griefcraft.lwc.LWCPlugin.onEnable(LWCPlugin.java:282)
[08:57:38] [Server thread/WARN]: 	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:264)
[08:57:38] [Server thread/WARN]: 	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:339)
[08:57:38] [Server thread/WARN]: 	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:403)
[08:57:38] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_13_R2.CraftServer.enablePlugin(CraftServer.java:431)
[08:57:38] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_13_R2.CraftServer.enablePlugins(CraftServer.java:345)
[08:57:38] [Server thread/WARN]: 	at net.minecraft.server.v1_13_R2.DedicatedServer.init(DedicatedServer.java:214)
[08:57:38] [Server thread/WARN]: 	at net.minecraft.server.v1_13_R2.MinecraftServer.run(MinecraftServer.java:702)
[08:57:38] [Server thread/WARN]: 	at java.lang.Thread.run(Unknown Source)
```

**Comment by pop4959** [comment]
@almateoskott I'm assuming you upgraded from some prior version. What would that be? My guess would be 2.0.7 based on the output, however I'm not entirely certain.

Are there any other details you can provide regarding the upgrade process? Is this the first time you are running a new version of the plugin? LWC should automatically upgrade your database, but it looks like it encountered an error, as if it tried to upgrade before and failed (perhaps you force quit the server while it was upgrading). If possible, you may want to check the state of the lwc_blocks table, and include a screenshot of the first few entries.

Also, if you use Discord, you might find it easier to join our support channel through the link on [this page](https://github.com/Tsuser1/Modern-LWC#support). For technical issues like this it is often the easier to troubleshoot in real time.

Thanks :)

**Comment by pop4959** [comment]
Similar issue to #63, ran 2.1.1 resulting in an incomplete lwc_blocks table before running 2.1.2 which fixes that issue, preventing it from properly running the upgrade process again. If anyone else has this problem the best approach seems to be to back up the database, drop the lwc_blocks table, and run 2.1.2 again. Before doing so, delete any entries in lwc_protections that have a block id *and* block name that are null, as this appears to cause issues, although it is uncertain how such malformed entries could have occurred.
