### ISSUE TITLE
Database connection 

### ISSUE THREAD

**Issue by ducitymp** [Tsuser1/Modern-LWC#85]
**LWC Version (/lwc admin version):** 1.9.4
**Server version (/version):** 1.12.2

**Short five word summary of issue:** Database randomly losses connection.

**Detailed description of problem:**
It looks like the plugin losses the connection to the database while other plugins don't. It happens at random moments.

**If there was an error in console, put it here:**
```
[00:59:43] [Server thread/WARN]: com.mysql.jdbc.exceptions.jdbc4.CommunicationsException: The last packet successfully received from the server was 763,877 milliseconds ago.  The last packet sent successfully to the server was 763,877 milliseconds ago. is longer than the server configured value of 'wait_timeout'. You should consider either expiring and/or testing connection validity before use in your application, increasing the server configured values for client timeouts, or using the Connector/J connection property 'autoReconnect=true' to avoid this problem.
[00:59:43] [Server thread/WARN]: 	at sun.reflect.GeneratedConstructorAccessor221.newInstance(Unknown Source)
[00:59:43] [Server thread/WARN]: 	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
[00:59:43] [Server thread/WARN]: 	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
[00:59:43] [Server thread/WARN]: 	at com.mysql.jdbc.Util.handleNewInstance(Util.java:425)
[00:59:43] [Server thread/WARN]: 	at com.mysql.jdbc.SQLError.createCommunicationsException(SQLError.java:990)
[00:59:43] [Server thread/WARN]: 	at com.mysql.jdbc.MysqlIO.send(MysqlIO.java:3746)
[00:59:43] [Server thread/WARN]: 	at com.mysql.jdbc.MysqlIO.sendCommand(MysqlIO.java:2509)
[00:59:43] [Server thread/WARN]: 	at com.mysql.jdbc.MysqlIO.sqlQueryDirect(MysqlIO.java:2680)
[00:59:43] [Server thread/WARN]: 	at com.mysql.jdbc.ConnectionImpl.execSQL(ConnectionImpl.java:2480)
[00:59:43] [Server thread/WARN]: 	at com.mysql.jdbc.ConnectionImpl.setAutoCommit(ConnectionImpl.java:4811)
[00:59:43] [Server thread/WARN]: 	at com.griefcraft.sql.Database.setAutoCommit(Database.java:191)
[00:59:43] [Server thread/WARN]: 	at com.griefcraft.sql.Database.closeQuietly(Database.java:90)
[00:59:43] [Server thread/WARN]: 	at com.griefcraft.sql.Database.lambda$0(Database.java:85)
[00:59:43] [Server thread/WARN]: 	at com.google.common.cache.LocalCache.processPendingNotifications(LocalCache.java:1966)
[00:59:43] [Server thread/WARN]: 	at com.google.common.cache.LocalCache$Segment.runUnlockedCleanup(LocalCache.java:3650)
[00:59:43] [Server thread/WARN]: 	at com.google.common.cache.LocalCache$Segment.postWriteCleanup(LocalCache.java:3626)
[00:59:43] [Server thread/WARN]: 	at com.google.common.cache.LocalCache$Segment.lockedGetOrLoad(LocalCache.java:2289)
[00:59:43] [Server thread/WARN]: 	at com.google.common.cache.LocalCache$Segment.get(LocalCache.java:2211)
[00:59:43] [Server thread/WARN]: 	at com.google.common.cache.LocalCache.get(LocalCache.java:4154)
[00:59:43] [Server thread/WARN]: 	at com.google.common.cache.LocalCache$LocalManualCache.get(LocalCache.java:5060)
[00:59:43] [Server thread/WARN]: 	at com.griefcraft.sql.Database.prepare(Database.java:354)
[00:59:43] [Server thread/WARN]: 	at com.griefcraft.sql.Database.prepare(Database.java:336)
[00:59:43] [Server thread/WARN]: 	at com.griefcraft.sql.PhysDB.loadProtection(PhysDB.java:940)
[00:59:43] [Server thread/WARN]: 	at com.griefcraft.sql.PhysDB.loadProtection(PhysDB.java:906)
[00:59:43] [Server thread/WARN]: 	at com.griefcraft.util.ProtectionFinder.tryLoadProtection(ProtectionFinder.java:299)
[00:59:43] [Server thread/WARN]: 	at com.griefcraft.util.ProtectionFinder.matchBlocks(ProtectionFinder.java:117)
[00:59:43] [Server thread/WARN]: 	at com.griefcraft.lwc.LWC.findProtection(LWC.java:1323)
[00:59:43] [Server thread/WARN]: 	at com.griefcraft.lwc.LWC.findProtection(LWC.java:1299)
[00:59:43] [Server thread/WARN]: 	at com.griefcraft.lwc.LWC.findProtection(LWC.java:1288)
[00:59:43] [Server thread/WARN]: 	at com.griefcraft.listeners.LWCPlayerListener.onPlayerInteract(LWCPlayerListener.java:665)
[00:59:43] [Server thread/WARN]: 	at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor81.execute(Unknown Source)
[00:59:43] [Server thread/WARN]: 	at org.bukkit.plugin.EventExecutor$2.execute(EventExecutor.java:70)
[00:59:43] [Server thread/WARN]: 	at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:78)
[00:59:43] [Server thread/WARN]: 	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62)
[00:59:43] [Server thread/WARN]: 	at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:515)
[00:59:43] [Server thread/WARN]: 	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:500)
[00:59:43] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_12_R1.event.CraftEventFactory.callPlayerInteractEvent(CraftEventFactory.java:236)
[00:59:43] [Server thread/WARN]: 	at net.minecraft.server.v1_12_R1.PlayerInteractManager.a(PlayerInteractManager.java:460)
[00:59:43] [Server thread/WARN]: 	at net.minecraft.server.v1_12_R1.PlayerConnection.a(PlayerConnection.java:991)
[00:59:43] [Server thread/WARN]: 	at net.minecraft.server.v1_12_R1.PacketPlayInUseItem.a(PacketPlayInUseItem.java:37)
[00:59:43] [Server thread/WARN]: 	at net.minecraft.server.v1_12_R1.PacketPlayInUseItem.a(PacketPlayInUseItem.java:5)
[00:59:43] [Server thread/WARN]: 	at net.minecraft.server.v1_12_R1.PlayerConnectionUtils.lambda$ensureMainThread$0(PlayerConnectionUtils.java:14)
[00:59:43] [Server thread/WARN]: 	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
[00:59:43] [Server thread/WARN]: 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
[00:59:43] [Server thread/WARN]: 	at net.minecraft.server.v1_12_R1.SystemUtils.a(SourceFile:46)
[00:59:43] [Server thread/WARN]: 	at net.minecraft.server.v1_12_R1.MinecraftServer.D(MinecraftServer.java:843)
[00:59:43] [Server thread/WARN]: 	at net.minecraft.server.v1_12_R1.DedicatedServer.D(DedicatedServer.java:426)
[00:59:43] [Server thread/WARN]: 	at net.minecraft.server.v1_12_R1.MinecraftServer.C(MinecraftServer.java:767)
[00:59:43] [Server thread/WARN]: 	at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:665)
[00:59:43] [Server thread/WARN]: 	at java.lang.Thread.run(Thread.java:745)
[00:59:43] [Server thread/WARN]: Caused by: java.net.SocketException: Connection reset
[00:59:43] [Server thread/WARN]: 	at java.net.SocketOutputStream.socketWrite(SocketOutputStream.java:113)
[00:59:43] [Server thread/WARN]: 	at java.net.SocketOutputStream.write(SocketOutputStream.java:153)
[00:59:43] [Server thread/WARN]: 	at java.io.BufferedOutputStream.flushBuffer(BufferedOutputStream.java:82)
[00:59:43] [Server thread/WARN]: 	at java.io.BufferedOutputStream.flush(BufferedOutputStream.java:140)
[00:59:43] [Server thread/WARN]: 	at com.mysql.jdbc.MysqlIO.send(MysqlIO.java:3728)
[00:59:43] [Server thread/WARN]: 	... 44 more
```

**Comment by pop4959** [comment]
I think it is a problem with your database. The plugin is already configured to automatically reconnect, as seen below. 

https://github.com/Tsuser1/Modern-LWC/blob/36c3caad3768c5223c5302900358000efd4b2fcc/src/main/java/com/griefcraft/sql/Database.java#L250

If you believe it is an issue with the plugin, please be ready to back up your claim, or otherwise provide a method of replicating the issue so that it can be confirmed as a bug.

Perhaps try testing without other plugins installed. If another plugin is blocking LWC from the database, this may fix the issue. Another thing you can try is to switch the database type to SQLite. If the problem was that the connection was failing in an unexpected way, it might fix the issue. If the problem was with the type of SQL server you were running, it may also fix the issue. Those are just a few ideas, but you can explore the issue on your own to see if anything helps.
